server:
  port: 8000
spring:
  application:
    name: gateway
  config:
    import: 'consul:'
  cloud:
    loadbalancer:
      ribbon:
        # Not needed since we excluded the dependency, but still good to add it here for better readability
        enabled: false
    consul:
      config: # Spring Boot Config Data Import
        data-key: application.yml
        prefix: config
        format: yaml
        default-context: defaults
      enabled: true
      discovery: # Get only services that are passing the health check
        query-passing: true
    gateway:
      routes:
        - id: multiplication
          uri: lb://multiplication/
          predicates:
            - Path=/challenges/**,/attempts,/attempts/**,/users/**
        - id: gamification
          uri: lb://gamification/
          predicates:
            - Path=/leaders
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - name: Retry
          args:
            retries: 3
            methods: GET,POST
logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: trace